### ISSUE TITLE
Consider adding support for AllJoyn

### ISSUE THREAD

**Issue by dotMorten** [rayshobby/opensprinkler#14]
Adding AllJoyn support out of the box for OpenSprinkler could really help integrating it with the future of Home Automation. The work required with the provided tools by the AllSeen Alliance is actually not that big.
Define all the methods, events and properties the sprinkler should expose using the XML introspection API and most of the code and interfaces are completely autogenerated for you, for a quick follow-on implementation of the interfaces.

https://allseenalliance.org/

**Comment by rayshobby** [comment]
Since OpenSprinkler is not a Linux based system (except OpenSprinkler Pi), it seems it would be quite difficult to add AllJoyn support.

**Comment by dotMorten** [comment]
There's also a NodeJS version of it

**Comment by dotMorten** [comment]
...most of the C code is cross platform. This isn't linux specific at all
